setScene();
addLight();
createFloor();
createMarble();
addShapes();
document.addEventListener( 'keydown', onKeyDown, false );
document.addEventListener( 'keyup', onKeyUp, false );
animate();
rainbow();
window.addEventListener('resize', resizeScene);